app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
| @author  Gustavo Ocanto <gustavoocanto@gmail.com>
|
*/

Route::controllers([
    'auth'     => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

//user account verification
Route::get('verification/{token}', 'UserController@accountVerification');

// home control
Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::group(['prefix' => 'home'], function () {
    Route::get('/', 'HomeController@index');
});

//Product list
Route::get('products', ['uses' => 'ProductsController@index', 'as' => 'products']);

//Orders Reports
Route::get('orders/report/{type}/{filter}', ['uses' => 'OrdersController@reports', 'as' => 'orders.report']);

//Busqueda General
Route::get('search/', 'ProductsController@searchAll');

Route::get('categories', 'CategoriesController@index');

//Acceso Usuario General(Admin,Persona,Empresa)
Route::group(['prefix' => 'user', 'roles' => array_keys(trans('globals.roles')), 'middleware' => ['auth', 'roles']], function () {
    Route::get('dashboard', 'UserController@dashBoard');

    Route::get('/', 'UserController@profile');

    Route::get('profile', 'UserController@profile');

    Route::post('profile/save', 'UserController@saveProfile');

    Route::post('profile/disable', 'UserController@disableProfile');

    Route::post('profile/enable', 'UserController@activeProfile');

    Route::post('upload', 'UserController@upload');

    //Address
    Route::get('address/', 'AddressesController@index'); //list

    Route::post('address/default', 'AddressesController@setDefault'); //set default

    Route::get('address/create', 'AddressesController@create');  //create form

    Route::get('address/{id}/edit', 'AddressesController@edit'); //edit form

    Route::put('address/store', 'AddressesController@store'); //store

    Route::put('address/{id}', 'AddressesController@update'); //update

    Route::post('address/delete', 'AddressesController@destroy'); //delete

    //Store Cart

    Route::get('user/orders/updateQuantity/{orderId}/{orderDetailId}/{newValue}', ['uses' => 'OrdersController@updateQuantity', 'as' => 'orders.update_order_quantity']);

    Route::get('product/save/{product}', ['uses' => 'OrdersController@saveForLater', 'as' => 'orders.save_for_later']);

    Route::get('orders/moveFrom/{origin}/to/{destination}/{productId}', ['uses' => 'OrdersController@moveFromOrder', 'as' => 'orders.move_from_order']);

    Route::get('orders/addToOrder/{orderId}/{productId}', ['uses' => 'OrdersController@addToOrderById', 'as' => 'orders.add_to_order_by_id']);

    Route::get('orders/checkOut/', ['uses' => 'OrdersController@checkOut', 'as' => 'orders.check_out']);

    Route::get('orders/checkOut/address/{addressId}', ['uses' => 'OrdersController@checkOutResume', 'as' => 'orders.check_out_address']);

    Route::get('orders/placeOrder/{type}', ['uses' => 'OrdersController@placeOrder', 'as' => 'orders.place_order']);

    Route::get('orders', ['uses' => 'OrdersController@usersOrders', 'as' => 'orders.show_orders']);

    //filtered by dates
    Route::post('orders', ['uses' => 'OrdersController@usersOrders', 'as' => 'orders.show_orders']);

    Route::get('orders/cancel/{orderId}', ['uses' => 'OrdersController@cancel', 'as' => 'orders.cancel']);

    Route::get('orders/showSeller/{orderId}', ['uses' => 'OrdersController@showSellerOrder', 'as' => 'orders.show_seller_order']);

    Route::get('orders/show/{orderId}', ['uses' => 'OrdersController@showOrder', 'as' => 'orders.show_order']);

    Route::get('orders/rate/{orderId}', ['uses' => 'OrdersController@rateOrder', 'as' => 'orders.rate_order']);

    //Route used to login an user and send it back to the product show

    Route::get('logAndShow/{productId}', ['uses' => 'ProductsController@show', 'as' => 'products.log_and_show']);

    Route::get('orders/close/{order_id}', ['uses' => 'OrdersController@closeOrder', 'as' => 'orders.close']);

    Route::get('modalSeeKeysPurchased', ['uses' => 'VirtualProductOrdersController@modalSeeKeysPurchased', 'as' => 'VirtualProductOrders.modalSeeKeysPurchased']);

    Route::get('showKeyVirtualProductPurchased/{idProduct}/{idOrder}', ['uses' => 'VirtualProductOrdersController@showKeyVirtualProductPurchased', 'as' => 'VirtualProductOrders.showKeyVirtualProductPurchased']);

    Route::get('orders/comment/{order_id}', ['uses' => 'OrdersController@commentOrder', 'as' => 'orders.comment']);

    Route::post('orders/storeComment', ['uses' => 'OrdersController@storeComment', 'as' => 'orders.store_comment']);

    Route::get('orders/delete/{order_id}/{type}', ['uses' => 'OrdersController@destroy', 'as' => 'orders.delete']);

    //Rates
    Route::post('rates/seller', ['uses' => 'OrdersController@rateSeller', 'as' => 'orders.rate_seller']);

    Route::post('rates/product', ['uses' => 'OrdersController@rateProduct', 'as' => 'orders.rate_product']);

    //Freeproducts
    Route::put('freeproducts/subscribe/{id}', ['uses' => 'FreeProductsController@subscribe', 'as' => 'freeproducts.subscribe']);

    Route::get('myFreeProducts', ['uses' => 'FreeProductsController@myFreeProducts', 'as' => 'freeproducts.my_free_products']);
});

//Companies Routes
Route::group(['roles' => ['business', 'nonprofit', 'admin'], 'middleware' => ['auth', 'roles']], function () {
    Route::resource('productsGroup', 'ProductsGroupController');

    Route::get('products/create', ['uses' => 'ProductsController@create', 'as' => 'products.create']);

    Route::get('products/{id}/edit', ['uses' => 'ProductsController@edit', 'as' => 'products.edit']);

    Route::get('products/downloadExample', ['uses' => 'ProductsController@downloadExample', 'as' => 'products.downloadExample']);

    Route::post('products', ['uses' => 'ProductsController@store', 'as' => 'products.store']);

    Route::post('products/upload', ['uses' => 'ProductsController@upload', 'as' => 'products.upload']);

    Route::post('products/upload_key', ['uses' => 'ProductsController@upload_key', 'as' => 'products.upload_key']);

    Route::post('products/upload_software', ['uses' => 'ProductsController@upload_software', 'as' => 'products.upload_software']);

    Route::put('products/{id}', ['uses' => 'ProductsController@update', 'as' => 'products.update']);

    Route::get('modalAllKeys', ['uses' => 'VirtualProductsController@modalAllKeys', 'as' => 'virtualproducts.modalAllKeys']);

    Route::get('showAllKeys/{id}', ['uses' => 'VirtualProductsController@showAllKeys', 'as' => 'virtualproducts.showAllKeys']);

    Route::get('deleteKey/{id}', ['uses' => 'VirtualProductsController@deleteKey', 'as' => 'virtualproducts.deleteKey']);

    Route::post('products/change/status/{id}', ['uses' => 'ProductsController@changeStatus', 'as' => 'products.change_status']);

    Route::get('orders/usersOrders', ['uses' => 'OrdersController@usersOrders', 'as' => 'orders.pendingOrders']);

    //filtered by dates
    Route::post('orders/usersOrders', ['uses' => 'OrdersController@usersOrders', 'as' => 'orders.pendingOrders']);

    Route::get('orders/start/{order_id}', ['uses' => 'OrdersController@startOrder', 'as' => 'orders.start']);

    Route::get('orders/send/{order_id}', ['uses' => 'OrdersController@sendOrder', 'as' => 'orders.send']);

    Route::get('virtualDelivery/{orderId}/{productId}', ['uses' => 'OrdersController@deliveryVirtualProduct', 'as' => 'orders.virtualDelivery']);

    Route::get('freeproducts/{OrderId}/create', ['uses' => 'FreeProductsController@create', 'as' => 'freeproducts.create']);

    Route::post('freeproducts', ['uses' => 'FreeProductsController@store', 'as' => 'freeproducts.store']);

    Route::get('products/myProducts', ['uses' => 'ProductsController@myProducts', 'as' => 'products.myProducts']);

    Route::post('/products/delete_img', ['uses' => 'ProductsController@deleteImg', 'as' => 'products.deleteImg']);
});

//Wpanel Routes
Route::group(['prefix' => 'wpanel', 'roles' => 'admin', 'middleware' => ['auth', 'roles']], function () {
    Route::resource('/', 'WpanelController');

    Route::resource('category', 'CategoriesController');

    Route::post('category/upload', ['uses' => 'CategoriesController@upload', 'as' => 'category.upload']);

    Route::get('categories', ['uses' => 'CategoriesController@showList', 'as' => 'categories']);

    Route::resource('productsdetails', 'ProductDetailsController');

    Route::get('features', ['uses' => 'ProductDetailsController@index', 'as' => 'features']);

    Route::resource('profile', 'CompanyController');
});

/*
 * WISH LISTS
 * here you will be able to find all the routes related to users wish list
 */

Route::group(['prefix' => 'wishes', 'roles' => array_keys(trans('globals.roles')), 'middleware' => ['auth', 'roles']], function () {

    //create
    Route::get('/create', ['uses' => 'OrdersController@createWishList', 'as' => 'orders.create_wish_list']);

    //add into a specific wish list by id
    Route::get('/{id}/products', ['uses' => 'OrdersController@showWishList', 'as' => 'orders.show_wish_list_by_id']);

    //list
    Route::get('/', ['uses' => 'OrdersController@showWishList', 'as' => 'orders.show_wish_list']);

    //user directory
    Route::get('/directory', ['uses' => 'OrdersController@wishListDirectory', 'as' => 'orders.show_list_directory']);

    //store
    Route::post('/store', ['uses' => 'OrdersController@storeWishList', 'as' => 'orders.store_list']);
});

// Acceso sin login Cambios para poder crear carrito y listas

Route::get('user/orders/addTo/{destination}/{productId}', ['uses' => 'OrdersController@addToOrder', 'as' => 'orders.add_to_order']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
| @author  Gustavo Ocanto <gustavoocanto@gmail.com>
|
*/

Auth::routes();

// home
Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::group(['prefix' => 'home'], function () {
    Route::get('/', 'HomeController@index');
});

//users routes
require __DIR__.'/web/users.php';

//business routes
require __DIR__.'/web/business.php';

//Wpanel Routes
require __DIR__.'/web/wpanel.php';

//products lists
require __DIR__.'/web/products.php';

//wish lists
require __DIR__.'/web/wish_lists.php';

//orders lists
require __DIR__.'/web/orders.php';

//about
require __DIR__.'/web/about.php';

//utilities
require __DIR__.'/web/utilities.php';

app/Product.php
<?php

namespace app;

/*
 * Antvel - Products Model
 *
 * @author  Gustavo Ocanto <gustavoocanto@gmail.com>
 */

use App\Category;
use App\Eloquent\Model;

class Product extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'products';
    protected $appends = ['num_of_reviews'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'category_id',
        'user_id',
        'name',
        'description',
        'price',
        'stock',
        'features',
        'barcode',
        'condition',
        'rate_val',
        'rate_count',
        'low_stock',
        'status',
        'parent_id',
    ];

    protected $hidden = ['details', 'created_at'];

    public function details()
    {
        return $this->hasMany('App\OrderDetail');
    }

    public function categories()
    {
        return $this->belongsTo('App\Category', 'category_id');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function group()
    {
        return $this->hasMany('App\Product', 'products_group', 'products_group');
    }

    public static function create(array $attr = [])
    {
        if (isset($attr['features']) && is_array($attr['features'])) {
            $attr['features'] = json_encode($attr['features']);
        }

        return parent::create($attr);
    }

    public function getLastCommentsAttribute()
    {
        return $this->details->take(5);
    }

    public function getFirstImageAttribute()
    {
        $features_array = $this->features;

        return $features_array['images'][0];
    }

    public function getFeaturesAttribute()
    {
        return json_decode($this->attributes['features'], true);
    }

    public function scopeActives($query)
    {
        return $query->where('status', 1)
                     ->where('stock', '>', 0);
    }

    public function scopeInactives($query)
    {
        return $query->where('status', 0);
    }

    public function scopeSearch($query, $seed)
    {
        return $query->where('name', 'like', '%'.$seed.'%')
            ->orWhere('description', 'like', '%'.$seed.'%')
            ->orWhere('features', 'like', '%'.$seed.'%')
            ->orWhere('brand', 'like', '%'.$seed.'%')
            ->orWhere('tags', 'like', '%'.$seed.'%');
    }

    public function scopeRefine($query, $filters)
    {
        foreach ($filters as $key => $value) {
            switch ($key) {
                case 'category':
                    $children = \Cache::remember('progeny_of_'.$value, 15, function () use ($value) {
                        Category::progeny($value, $children, ['id']);

                        return $children;
                    });
                    $children[] = ['id' => $value * 1];
                    $query->whereIn('category_id', $children);
                break;

                case 'conditions':
                    $query->where('condition', 'LIKE', $value);
                break;

                case 'brands':
                   $query->where('brand', 'LIKE', $value);
                break;

                case 'min':
                case 'max':
                    $min = array_key_exists('min', $filters) ? (trim($filters['min']) != '' ? $filters['min'] : '') : '';
                    $max = array_key_exists('max', $filters) ? (trim($filters['max']) != '' ? $filters['max'] : '') : '';

                    if ($min != '' && $max != '') {
                        $query->whereBetween('price', [$min, $max]);
                    } elseif ($min == '' && $max != '') {
                        $query->where('price', '<=', $max);
                    } elseif ($min != '' && $max == '') {
                        $query->where('price', '>=', $min);
                    }
                break;

                default:
                    if ($key != 'category_name' && $key != 'search' && $key != 'page') {

                        //changing url encoded character by the real ones
                        $value = urldecode($value);

                        //applying filter to json field
                        $query->whereRaw("features LIKE '%\"".$key.'":%"%'.str_replace('/', '%', $value)."%\"%'");
                    }
                break;
            }
        }
    }

    public function scopeName($query, $input)
    {
        if (trim($input) != '') {
            $query->where('name', 'LIKE', "%$input%");
        }
    }

    public function scopeType($query, $input)
    {
        if (count($input) > 0) {
            $query->whereIn('category_id', $input);
        }
    }

    public function getStatusLettersAttribute()
    {
        if ($this->status == 0) {
            return trans('globals.inactive');
        }

        return trans('globals.active');
    }

    public function scopeFree($query)
    {
        if (!config('app.offering_free_products')) {
            $query->where('type', '<>', 'freeproduct');
        }
    }

    /**
     * Products tags filter.
     *
     * @param [object] $query, which is the laravel builder
     * @param [string] $attr,  which is used to evaluate the where In (categories requiered)
     * @param [array]  $data,  which is the info to be evaluated
     */
    public function scopeLike($query, $attr = [], $search = [])
    {
        //if the search contains a string of words, we split them in an array
        if (!is_array($search)) {
            $search = explode(' ', preg_replace('/\s+/', ' ', trim($search)));
        }

        $needle = '(';

        if (!is_array($attr)) {
            $attr = [$attr];
        }
        foreach ($attr as $key) {
            foreach ($search as $word) {
                if (trim($word) != '') {
                    $needle .= $key." like '%".$word."%' or ";
                }
            }
        }

        $needle = rtrim($needle, ' or ').')';

        $query->whereRaw($needle);

        return $query;
    }

    /**
     * categories filter.
     *
     * @param [object] $query, which is the laravel builder
     * @param [string] $attr,  which is used to evaluate the where In (categories requiered)
     * @param [array]  $data,  which is the info to be evaluated
     */
    public function scopeInCategories($query, $attr, $data = [])
    {
        if (count($data) > 0 && empty($data['category'])) {
            $query->whereIn($attr, $data);
        } elseif (isset($data['category'])) {
            $query->where($attr, '=', $data['category']);
        }

        return $query;
    }

    public function getNumOfReviewsAttribute()
    {
        return $this->rate_count.' '.\Lang::choice('store.review', $this->rate_count);
    }
}

resources/views/partial/breadcrumbs.blade.php
<div class="navbar-wrapper container">
	{!! Breadcrumbs::render('productDetail', $product) !!}
</div>

resources/views/partial/footer.blade.php
<div class="container">
	<div class="row">
		<div class="col-xs-4 col-sm-4 col-md-4 menu">
			<?php $menu=\Menu::help(true); ?>
			<h3>{{ trans('globals.company_label') }}</h3>
			<ul>
				@foreach ($menu as $item)
					<li><a href = '{{ $item['route'] }}'>{{ $item['text'] }}</a></li>
				@endforeach
			</ul>
		</div>

		<div class="col-xs-4 col-sm-4 col-md-4 menu">
			<h3>{{ trans('globals.social_label') }}</h3>
			<ul>
				<li><a href="https://www.facebook.com/{{ $main_company['facebook'] }}" target="_blank">{{ trans('globals.facebook_label') }}</a></li>
				<li><a href="https://twitter.com/{{ $main_company['twitter'] }}" target="_blank">{{ trans('globals.twitter_label') }}</a></li>
				<li><a href="https://plus.google.com/u/0/{{ $main_company['google_plus'] }}" target="_blank">{{ trans('globals.google_label') }}</a></li>
			</ul>
		</div>

		<div class="col-xs-4 col-sm-4 col-md-4 newsletter" ng-controller = "NewslettersCtrl">
			@if (\Auth::user())
				<p>{{ trans('globals.reach_us_msg') }}</p>
				<p><strong><a href="/contact"><span class="glyphicon glyphicon-envelope"></span>&nbsp;{{ trans('globals.send_a_email_label') }}</a></strong></p>
			@else
				<div class="signup clearfix">
					<p>{{ trans('user.newsletter_sign_up') }}</p>
					<form>
						<input type="text" ng-model = "newsEmail"  class = "form-control input-sm" placeholder = "{{ trans('user.your_email_address_label') }}">
						<input type="button" ng-click = "save()" value = "{{ trans('user.sign_up_label') }}">
					</form>
				</div>
			@endif
		</div>

	</div>

	<div class="row credits">
		<div class="col-md-12">
			{{ trans('globals.power_by_label') }}&nbsp;<a href="http://antvel.com">{{ trans('globals.antvel_eCommerce') }}</a>
		</div>
	</div>

</div>

@section('scripts')
    @parent
        <script>
            (function(app){
	                app.controller('NewslettersCtrl', function($scope, $window, notify)
					{
					  	$scope.newsEmail = '';
					  	$scope.save = function()
					  	{
					  		if ($scope.newsEmail.trim() != '') {
					  			$window.location.href = '/register?email='+$scope.newsEmail;
					  		} else {
					  			notify({ duration:5000, messageTemplate: '<strong>{{ trans('globals.validation_error_label') }}</strong><br><br><p>{{ trans('globals.newsletter_email_error') }}</p>', classes: 'alert alert-danger' });
					  		}
					  	};
					});
            })(angular.module("AntVel"));
        </script>
    @stop

resources/views/partial/navigation.blade.php
<div class="navbar-wrapper container">
	<nav class="navbar navbar-inverse navbar-static-top">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<div class="navbar-brand">
				<a href="/home" class="navbar-brand">
					@if($main_company['logo'])
						<span class="navbar-brand-text">
							<img src="{{$main_company['logo']}}" alt="">
						</span>
					@else
						<span class="navbar-brand-text">{{ $main_company['name'] }}</span>
					@endif

					@if(isset($main_company['slogan']))
						<span class="navbar-brand-slogan">{{$main_company['slogan']}}</span>
					@endif
				</a>
			</div>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">

				@include('user.partial.menu_top')

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
						<span class="fui fui-heart"></span>{{ trans('store.wish_list') }}
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="{{ route('orders.show_wish_list') }}">{{ trans('store.wish_list') }}</a></li>
						<li><a href="{{ route('orders.show_list_directory') }}">{{ trans('store.your_wish_lists') }}</a></li>
					</ul>
				</li>

				<li class="dropdown">
					<a href="#cart" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
						@if(Auth::user()&&Auth::user()->getCartCount())
						<span class="badge badge-cart">{{ Auth::user()->getCartCount() }} </span>
						@elseif(!Auth::user() && is_array(Session::get('user.cart_content')) && array_sum(Session::get('user.cart_content')))
						<span class="badge badge-cart">{{ array_sum(Session::get('user.cart_content')) }} </span>
						@endif

						<span class="glyphicon glyphicon-shopping-cart"></span>{{ trans('store.cart') }}
						<span class="caret"></span>
					</a>

                    @if(Auth::user() && Auth::user()->getCartCount() > 0)
                        <ul class="dropdown-menu cart" role="menu">
                            @foreach(Auth::user()->getCartContent() as $orderDetail)
                                <li>
                                    <a href="{{ route('products.show',[$orderDetail->product->id]) }}" >

                                            <img src="{{ $orderDetail->product->FirstImage }}" alt="{{ $orderDetail->product->name }}" width="32" height="32" style="float: left; margin-right: 2px"/>
                                            {{ $orderDetail->product->name }}
                                             - {{ trans('store.quantity') }}: {{ $orderDetail->quantity }}

                                    </a>
                                </li>
                            @endforeach
                            <li><a class="btn btn-default" href="{{ route('orders.show_cart') }}" role="button">{{ trans('store.view_cart') }}</a></li>
                        </ul>
                    @elseif(!Auth::user() && is_array(Session::get('user.cart_content')))
                        <ul class="dropdown-menu cart" role="menu">
                        @foreach(Session::get('user.cart_content') as $product_id => $quantity)
                        @if($product=\App\Product::find($product_id))
                            <li>
                                <a href="{{ route('products.show',[$product_id]) }}" >

                                        <img src="{{ $product->first_image }}" width="32" height="32" style="float: left; margin-right: 2px"/>
                                        {{ $product->name }}
                                         - {{ trans('store.quantity') }}: {{ $quantity }}

                                </a>
                            </li>
                        @endif
                        @endforeach
                            <li><a class="btn btn-default" href="{{ route('orders.show_cart') }}" role="button">{{ trans('store.view_cart') }}</a></li>
                        </ul>
                    @endif
				</li>

				@if(Auth::user())
					<li class="dropdown " id="push-notices" ng-controller="PushNoticesController"  ng-click="check()" ng-focus="check()">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
							<span class="badge badge-notifications ng-hide" ng-cloak  ng-show="push">[[push]]</span>
							<span class="fui fui-chat"></span>{{ trans('globals.notices') }}
							<span class="visible-xs-inline">
								<span class="caret"></span>
							</span>
						</a>
						<ul class="dropdown-menu notices" role="menu" ng-if="notices.length">
							<li ng-repeat="notice in notices" class="[[notice.status]]">
								<a href="[[getLink(notice)]]" ng-click="check(notice)">[[getDesc(notice)]]</a>
							</li>
							<li>{!! link_to('user/notices/list', trans('globals.all')) !!}</li>
						</ul>
					</li>

					@if (config('app.offering_user_points'))
					<li>
						<a href="{{ route('paypal.buy_points') }}" ng-controller = "PushUsersPoints" ng-init = "pusher()">
							<span class="badge badge-points ng-hide" ng-cloak ng-show = "points" >[[ points | thousandSuffix ]]</span>
							<span class="fui fui-radio-unchecked"></span>{{ trans('store.price') }}
						</a>
					</li>
					@endif
				@endif

				@if (config('app.offering_free_products'))
					<li>
						<a href="{{ route('freeproducts.search') }}">
							<span class="fui fui-star-2"></span>{{ trans('globals.products') }}
							<span class="badge badge-freeproducts">{{ trans('globals.free') }}</span>
						</a>
					</li>
				@endif

			</ul>
			@include('partial.navigation_help')
		</div>
	</nav>

	<nav ng-controller="CategoriesController">
		{!! Form::model(Request::all(),['url'=> action('ProductsController@index'), 'method'=>'GET', 'id'=>'searchForm']) !!}
		<div class="input-group">
			<span class="input-group-btn categories-search">
				<button  type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
					<span ng-bind="catSelected.name || '{{ isset($categories_menu[Request::get('category')]['name']) ? $categories_menu[Request::get('category')]['name'] : trans('store.all_categories') }}'">
						{{ isset($categories_menu[Request::get('category')]['name']) ? $categories_menu[Request::get('category')]['name'] : trans('store.all_categories') }}
						</span> <span class="caret">
					</span>
				</button>
				<ul class="dropdown-menu" role="menu">
					@foreach($categories_menu as $categorie_menu)
						<li >
							<a href="javascript:void(0)"
							   ng-click="setCategorie({{ $categorie_menu['id'] }},'{{ $categorie_menu['name'] }}')" >
								{{ $categorie_menu['name'] }}
							</a>
						</li>
					@endforeach

				</ul>
			</span>
			<input type="hidden" name="category" value="[[refine() || '{{Request::get('category')}}']]"/>

			@include('partial.search_box',['angularController' => 'AutoCompleteCtrl', 'idSearch'=>'search'])

			<span class="input-group-btn">
				<button class="btn btn-default fui-search" type="submit"></button>
			</span>
		</div>
		{!! Form::close() !!}
		</nav>
</div>

resources/views/partial/navigation_basic.blade.php
<div class="navbar-wrapper">
    <nav class="navbar">
        <div class="container">
            <div class="navbar-header">
                <div class="navbar-brand">
                    <a href="/home" class="navbar-brand">
                        {{ $main_company['name'] }}
                        <br>
                        
                    </a>
                </div>
            </div>
            @include('partial.navigation_help')
        </div>
    </nav>
</div>